dist: trusty
language: c
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-5 libxcb-randr0-dev libconfig-dev libcairo2-dev libpango1.0-dev
script: make
