sudo: false
dist: trusty
language: c
compiler:
    - gcc
addons:
  apt:
    packages:
      - libxcb-randr0-dev
      - libconfig-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libasound2-dev
      - libiw-dev
      - docbook-xml
      - asciidoc-base
      - xsltproc
before_install:
    - export CPPFLAGS=-DOLD_LIBCONFIG
script:
  matrix:
      - make yabar && make install
      - make doc && make install
